name: flutter_overlay_window_example
description: Demonstrates how to use the flutter_overlay_window plugin.

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  multiavatar: ^0.1.5
  provider: ^6.0.2
  rename: ^2.0.0-dev.2
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  supercharged: ^2.1.1
#  flutter_app_version_checker: ^0.0.3
#  flutter_accessibility_service: ^0.2.2
  android_intent_plus: ^4.0.3
  flutter_overlay_window:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
